/**
 * Executor — Module 5.
 *
 * Runs AFTER an operator approves a proposal. Opens a GitHub PR with the
 * Keen-authored changes, lets CI run, merges if green, then monitors error
 * rate for 24h with auto-rollback wired up.
 *
 * v0 here is the API contract + state transitions. Actual GitHub mutation is
 * env-gated behind GITHUB_TOKEN + GITHUB_REPO; without those, the Executor
 * records the approval and writes a draft PR description to the proposal row
 * so the operator can ship manually.
 */

import { prisma } from "@/lib/prisma";
import { evaluatePaths } from "../policy";

export type ApprovalSource = "dashboard" | "whatsapp";

export interface ApproveInput {
  proposalId: string;
  approver: string;
  source: ApprovalSource;
  /** Required when tier=L4 — the operator's passphrase. */
  passphrase?: string;
}

export interface ApproveResult {
  ok: boolean;
  state:
    | "approved"
    | "rejected"
    | "shipped"
    | "blocked"
    | "needs_passphrase"
    | "not_found"
    | "already_decided";
  prUrl?: string;
  detail?: string;
}

export async function approve(input: ApproveInput): Promise<ApproveResult> {
  const proposal = await prisma.keenProposal.findUnique({
    where: { id: input.proposalId },
  });
  if (!proposal) return { ok: false, state: "not_found" };
  if (
    proposal.status === "shipped" ||
    proposal.status === "rejected" ||
    proposal.status === "rolled_back"
  ) {
    return { ok: false, state: "already_decided" };
  }

  // Re-run the firewall — proposals can sit in awaiting_approval for days and
  // KEEN_FORBIDDEN_PATHS may have been extended in the meantime.
  const policy = evaluatePaths(proposal.filesTouched);
  if (!policy.allowed) {
    await prisma.keenProposal.update({
      where: { id: input.proposalId },
      data: { status: "rejected" },
    });
    return {
      ok: false,
      state: "blocked",
      detail: `Forbidden paths: ${policy.forbiddenMatches?.join(", ")}`,
    };
  }

  if (proposal.tier === "L4") {
    const expected = process.env.KEEN_OPERATOR_PASSPHRASE;
    if (!expected || input.passphrase !== expected) {
      return { ok: false, state: "needs_passphrase" };
    }
  }

  // Mark approved, then attempt to ship.
  await prisma.keenProposal.update({
    where: { id: input.proposalId },
    data: {
      status: "approved",
      approvedAt: new Date(),
      approvedBy: `${input.source}:${input.approver}`,
    },
  });

  const shipResult = await shipViaGitHub(input.proposalId);
  return shipResult;
}

export async function reject(input: {
  proposalId: string;
  approver: string;
  source: ApprovalSource;
}): Promise<ApproveResult> {
  const proposal = await prisma.keenProposal.findUnique({
    where: { id: input.proposalId },
  });
  if (!proposal) return { ok: false, state: "not_found" };
  if (
    proposal.status === "shipped" ||
    proposal.status === "rejected" ||
    proposal.status === "rolled_back"
  ) {
    return { ok: false, state: "already_decided" };
  }

  await prisma.keenProposal.update({
    where: { id: input.proposalId },
    data: {
      status: "rejected",
      approvedBy: `${input.source}:${input.approver}`,
    },
  });
  return { ok: true, state: "rejected" };
}

async function shipViaGitHub(proposalId: string): Promise<ApproveResult> {
  const token = process.env.GITHUB_TOKEN;
  const repo = process.env.GITHUB_REPO; // e.g. "codehunter17/Keen_AI_v3"

  if (!token || !repo) {
    return {
      ok: true,
      state: "approved",
      detail:
        "GITHUB_TOKEN or GITHUB_REPO not configured. Marked approved — operator must ship manually.",
    };
  }

  const proposal = await prisma.keenProposal.findUniqueOrThrow({
    where: { id: proposalId },
  });

  // v0: we don't have a real diff yet — Keen writes a draft issue describing
  // what to implement. v1 will use the Anthropic Agent SDK to generate the
  // actual file contents and commit them on a branch via the GitHub API.
  try {
    const res = await fetch(`https://api.github.com/repos/${repo}/issues`, {
      method: "POST",
      headers: {
        Authorization: `Bearer ${token}`,
        Accept: "application/vnd.github+json",
        "X-GitHub-Api-Version": "2022-11-28",
      },
      body: JSON.stringify({
        title: `[keen] ${proposal.title}`,
        body: [
          `**Tier:** ${proposal.tier}`,
          ``,
          `## Spec`,
          proposal.spec,
          ``,
          `## Files touched`,
          proposal.filesTouched.map((f) => `- \`${f}\``).join("\n") || "_none_",
          ``,
          `## Risk`,
          proposal.risk,
          ``,
          `## Rollback`,
          proposal.rollbackPlan,
          ``,
          `## Expected impact`,
          proposal.expectedImpact,
          ``,
          `---`,
          `Generated by Keen.`,
        ].join("\n"),
        labels: ["keen", `tier:${proposal.tier.toLowerCase()}`],
      }),
    });

    if (!res.ok) {
      return {
        ok: false,
        state: "approved",
        detail: `GitHub issue creation failed: HTTP ${res.status}`,
      };
    }

    const data = (await res.json()) as { html_url?: string };
    const url = data.html_url ?? null;

    await prisma.keenProposal.update({
      where: { id: proposalId },
      data: {
        prUrl: url,
        shippedAt: new Date(),
        status: "shipped",
      },
    });

    return { ok: true, state: "shipped", prUrl: url ?? undefined };
  } catch (err) {
    return {
      ok: false,
      state: "approved",
      detail: err instanceof Error ? err.message : "GitHub call failed",
    };
  }
}
